---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - apt:
        name: nginx
      when: ansible_os_family == "Fedora"
  - name: Install the spotify flatpak
    flatpak:
      name:  https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref
      state: present

  - name: Install the gedit flatpak package
    flatpak:
      name: https://git.gnome.org/browse/gnome-apps-nightly/plain/gedit.flatpakref
      state: present

  - name: Install the gedit package from flathub for current user
    flatpak:
      name: org.gnome.gedit
      state: present
      method: user

  - name: Install the Gnome Calendar flatpak from the gnome remote system-wide
    flatpak:
      name: org.gnome.Calendar
      state: present
      remote: gnome

  - name: Remove the gedit flatpak
    flatpak:
      name: org.gnome.gedit
      state: absent